resources:
  - machineset.yml

transformers:
  - |-
    apiVersion: builtin
    kind: LabelTransformer
    metadata:
      name: machine-set-custom-labels-transformer
    labels:
      node-role.kubernetes.io/monitoring: ''
      node-role.kubernetes.io/infra: ''
    fieldSpecs:
      - path: spec/template/spec/metadata/labels
        create: true